"""add main tables

Revision ID: 9d538fba92b0
Revises:
Create Date: 2025-09-26 08:51:52.377335+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from app.core.config import settings

# revision identifiers, used by Alembic.
revision: str = "9d538fba92b0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=1000), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("username", name=op.f("uq_user_username")),
        schema=settings.postgres_db_schema,
    )
    op.create_index(
        op.f("ix_user_email"),
        "user",
        ["email"],
        unique=True,
        schema=settings.postgres_db_schema,
    )
    op.create_index(
        op.f("ix_user_id"),
        "user",
        ["id"],
        unique=False,
        schema=settings.postgres_db_schema,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_id"), table_name="user", schema=settings.postgres_db_schema)
    op.drop_index(op.f("ix_user_email"), table_name="user", schema=settings.postgres_db_schema)
    op.drop_table("user", schema=settings.postgres_db_schema)
    # ### end Alembic commands ###
