"""init tables

Revision ID: cda7d0878abb
Revises:
Create Date: 2025-09-19 19:46:26.791583+00:00

"""

import os
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cda7d0878abb"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=1000), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("username", name=op.f("uq_user_username")),
        schema=f"{os.getenv('POSTGRES_DB_SCHEMA')}",
    )
    op.create_index(
        op.f("ix_user_email"),
        "user",
        ["email"],
        unique=True,
        schema=f"{os.getenv('POSTGRES_DB_SCHEMA')}",
    )
    op.create_index(
        op.f("ix_user_id"),
        "user",
        ["id"],
        unique=False,
        schema=f"{os.getenv('POSTGRES_DB_SCHEMA')}",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_id"), table_name="user", schema=f"{os.getenv('POSTGRES_DB_SCHEMA')}"
    )
    op.drop_index(
        op.f("ix_user_email"), table_name="user", schema=f"{os.getenv('POSTGRES_DB_SCHEMA')}"
    )
    op.drop_table("user", schema=f"{os.getenv('POSTGRES_DB_SCHEMA')}")
    # ### end Alembic commands ###
